name: latlong_formatter
description: String formatting for Latitudes and Longitudes.
version: 1.0.0
repository: https://github.com/philseeley/latlong_formatter

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  intl:
  collection:
  format:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
