name: latlong_formatter
description: String formatting for Latitudes and Longitudes.
version: 2.0.0
repository: https://github.com/philseeley/latlong_formatter

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  intl: ^0.18.1
  format: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
