name: latlong_formatter
description: String formatting for Latitudes and Longitudes using templating.
version: 2.0.2
repository: https://github.com/philseeley/latlong_formatter

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  intl: ^0.20.2
  format: ^1.2.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0
